### ISSUE TITLE
How to disable this error:  cannot convert 'bool' to 'ComboBoxItem*' 

### ISSUE THREAD

**Issue by Liu-shua** [Pinsius/PinGUI#3]
../PinGUI/GUI_Elements/ComboBox.cpp:41:22: error: cannot convert 'bool' to 'Comb                                                                                                                                                                                               oBoxItem*' in initialization
     _rollbackVect(0,0)
                      ^

**Comment by Pinsius** [comment]
Hello @Liu-shua, problem was in ComboBox constructor(where the incorrect constructor of ComboBoxItem in initList was called). I uploaded the fixed cpp file that will hopefully fix this issue.
