### ISSUE TITLE
code's bugs

### ISSUE THREAD

**Issue by DarkCat5501** [Pinsius/PinGUI#4]
it is really helpful but the code has just so much error and a lot of variables that are not used for anything. In Code::blocks for example it was not so difficult to setup but i had to go all over the header files and the cpp ones deleting unused variables and adjusting function to properly return their contents.
You should clean the code a bit.

**Comment by i582** [comment]
heh, the repository has been abandoned for 2 years :) I am surprised to see someone in such an old repository. By the way, I also create gui on the SDL for my term paper (https://github.com/i582/component-sdl2) but there is still a lot of work.

**Comment by Pinsius** [comment]
Hello, thanks for your feedback, even though im reacting later then you would expect. However I stopped the project long time ago, but decided to keep the repository here as I know that some pieces of the code might help someone (even though it was my first bigger project and I was learning as well, so the code is not perfect).

**Comment by DarkCat5501** [comment]
your code helped me lots, and at the end, looking at the code bases was really helpful, because i could learn how to deal with gui and start doing my own.
So,thank you!

**Comment by Pinsius** [comment]
I'm really glad to hear that. Thats the reason why I still keep the project on github, even with many flaws. Some people might find it useful and it will help them start their own libraries.
